apiVersion: v1
kind: ServiceAccount
metadata:
  name: aspen-mesh-oscillate-health
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aspen-mesh-oscillate-health
subjects:
  - kind: ServiceAccount
    name: aspen-mesh-oscillate-health
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: aspen-mesh-oscillate-health
  namespace: default
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      name: aspen-mesh-oscillate-health
      labels:
        job-name: aspen-mesh-oscillate-health
    spec:
      containers:
        - name: aspen-mesh-oscillate-health
          image: quay.io/tartale/tools:oscillate-health-latest
          imagePullPolicy: Always
          env:
            - name: INTERVAL
              value: "1200"
      serviceAccount: aspen-mesh-oscillate-health
      serviceAccountName: aspen-mesh-oscillate-health
      restartPolicy: OnFailure
---

